### ISSUE TITLE
Having problems getting this installed

### ISSUE THREAD

**Issue by fuzzygroup** [benpickles/medium-rb#2]
Hi, 

I really like what you've done here and I'd love to use it but I keep getting the error:

Could not find gem 'medium-rb' in any of the gem sources listed in your Gemfile or available on this machine.

when I bundle install with  gem 'medium-rb'.

Even a gem 'medium-rb', git: 'git@github.com:benpickles/medium-rb.git' doesn't work

What is the actual gemfile syntax to get this installed?

**Comment by benpickles** [comment]
The magical incantation is:

```
gem 'medium', github: 'benpickles/medium-rb'
```

Sorry, I should change the name of the repo to fix it :s I'll update this issue when I've done that.

**Comment by benpickles** [comment]
OK I've renamed the repository, your Gemfile should now have the following:

```
gem 'medium', github: 'benpickles/medium'
```

**Comment by fuzzygroup** [comment]
Thank you so much Ben.  Really appreciated.
